// netlify/functions/update-booking.js
// Admin-only: persist safe booking mutations to Netlify Blobs (cd1-bookings).
//
// Auth
//   Header:  x-admin-key: <ADMIN_DASH_PASSWORD>
//   503 — ADMIN_DASH_PASSWORD env var not configured
//   401 — key missing or wrong (timing-safe comparison)
//
// Input (POST JSON)
//   bookingId         — required string
//   updates           — required plain object, strict allowlist enforced
//   lastAction        — optional string (default: "admin_update_booking")
//   allowArchivedUpdate — optional boolean, required to mutate archived/test bookings
//
// Every successful write adds:
//   updatedAt, updatedByRole:"admin", updatedBy:"admin", lastAction
//
// Email triggers (via Resend — requires RESEND_API_KEY env var):
//   appointmentStatus → "confirmed"  OR  status → "Confirmed"
//   → confirmation email to customer with date, time window, and optional
//     customer-facing note. Never includes adminNotes or Stripe fields.
//
// Logging: bookingId + changed field NAMES only. Never logs values or secrets.
//
// Blocked fields (returns 400): payment, PII, price, tech assignment, flags.
// Unknown fields: returns 400.

const crypto = require('crypto');
const { json: secureJson, safeHttpUrl } = require('./_security');

let currentEvent;
const json = (statusCode, body) => secureJson(currentEvent, statusCode, body);

async function blobsStore(name) {
  const { getStore } = await import('@netlify/blobs');
  const siteID = process.env.NETLIFY_SITE_ID;
  const token  = process.env.NETLIFY_AUTH_TOKEN;
  return (siteID && token) ? getStore({ name, siteID, token }) : getStore(name);
}

// ── Status allowlists ────────────────────────────────────────────────────────

const ALLOWED_APPOINTMENT_STATUS = new Set([
  'pending_review', 'confirmed', 'canceled',
]);

const ALLOWED_JOB_STATUS = new Set([
  'not_started', 'en_route', 'in_progress', 'completed', 'closed', 'canceled',
]);

// Legacy values used by the existing admin UI — preserved for compatibility.
const ALLOWED_LEGACY_STATUS = new Set([
  'Pending Review', 'Reviewed', 'Contacted', 'Confirmed', 'Scheduled',
  'En Route', 'In Progress', 'Completed', 'Closed', 'Canceled', 'Problem',
  'Cancellation Requested', 'Cancelled', 'Rescheduled', 'No-Show', 'Paid',
]);

// ── Field allowlist (admin may write these fields only) ──────────────────────

const ALLOWED_FIELDS = new Set([
  // Appointment / job lifecycle
  'status', 'appointmentStatus', 'jobStatus',
  // Scheduling
  'confirmedDate', 'confirmedTime', 'confirmedTimeWindow',
  'preferredDate', 'preferredTime',
  // Admin workflow
  'adminReviewed', 'adminReviewedAt',
  'adminContacted', 'adminContactedAt',
  'adminNotes', 'customerNote',
  // Lifecycle timestamps
  'confirmedAt', 'startedAt', 'enRouteAt',
  'completedAt', 'closedAt', 'canceledAt',
  // Problem flags
  'hasProblem', 'lastProblem',
  // Payment collection state — display-only, separate from paymentStatus.
  // Used by admin when sending a payment link; never conflated with job lifecycle.
  'paymentLifecycle',
  // Payment link URL — generated by create-payment-link, admin persists here.
  'payLink',
  // Cancellation management — admin can review and resolve customer requests.
  'cancellationRequestStatus', 'cancellationResolvedAt', 'cancellationResolvedNote',
]);

// Explicitly blocked fields — produce a clear 400 instead of "unknown_field".
const BLOCKED_FIELDS = new Set([
  'paymentStatus', 'paymentIntentId',
  'amountAuthorizedCents', 'amountCapturedCents',
  'capturedAt', 'captureInitiatedAt',
  'stripeCustomerId', 'paymentMethodId', 'stripePaymentMethodId',
  'setupIntentId', 'cardOnFileStatus', 'cardOnFileSavedAt',
  'firstName', 'lastName', 'email', 'phone', 'address', 'zipCode',
  'totalPrice', 'packagePrice', 'package', 'vehicle', 'addOns',
  'archived', 'isTest',
  'assignedTech', 'assignedTechName',
]);

// String note fields — length-capped before storage.
const NOTE_FIELDS = new Set(['adminNotes', 'customerNote', 'lastProblem', 'cancellationResolvedNote']);
const NOTE_MAX = 1000;
// URL fields — longer cap for Stripe and other payment URLs.
const URL_FIELDS  = new Set(['payLink']);
const URL_MAX  = 2000;
// Cancellation request status values admin may set.
const CANCEL_REQ_STATUS = new Set(['requested', 'reviewed', 'resolved_approved', 'resolved_denied']);

// Boolean fields — must be actual booleans, not strings.
const BOOL_FIELDS = new Set(['adminReviewed', 'adminContacted', 'hasProblem']);

// Date and time fields — must be strings.
const DATE_FIELDS = new Set(['confirmedDate', 'preferredDate']);
const TIME_FIELDS = new Set(['confirmedTime', 'preferredTime', 'confirmedTimeWindow']);

// ── Helpers ──────────────────────────────────────────────────────────────────

function sanitize(value) {
  return (typeof value === 'string' ? value : String(value)).slice(0, NOTE_MAX);
}

// ── Confirmation email ────────────────────────────────────────────────────────
// Sent to customer when admin confirms the appointment.
// Must not expose: adminNotes, paymentIntentId, amounts, or internal fields.

async function sendConfirmationEmail(b) {
  const { RESEND_API_KEY, RESEND_FROM } = process.env;
  if (!RESEND_API_KEY) return { sent: false, reason: 'RESEND_API_KEY not configured' };
  if (!b.email)        return { sent: false, reason: 'no customer email on booking' };

  const name    = [b.firstName, b.lastName].filter(Boolean).join(' ') || 'Valued Customer';
  const first   = name.split(' ')[0];
  const service = b.package || b.service || 'Detailing Service';
  const vehicle = b.vehicleLabel || b.vehicle || b.vehicleCategory || '—';
  const date    = b.confirmedDate || '—';
  const window  = b.confirmedTimeWindow || b.confirmedTime || '—';
  const address = b.address || 'your specified location';

  const lines = [
    `Hi ${first},`,
    ``,
    `Your Cardetail1 appointment has been confirmed.`,
    ``,
    `  Booking ID:    ${b.id}`,
    `  Service:       ${service}`,
    `  Vehicle:       ${vehicle}`,
    `  Date:          ${date}`,
    `  Time window:   ${window}`,
    `  Location:      ${address}`,
  ];

  if (b.customerNote) {
    lines.push(``, `  Note:  ${b.customerNote}`);
  }

  lines.push(
    ``,
    `Payment:`,
    `  Payment details are handled separately. If a card authorization, payment`,
    `  link, or on-site payment is required, Cardetail1 will confirm those details`,
    `  with you directly.`,
    ``,
    `Need to make changes?`,
    `  Call or text: 551-313-2956`,
    `  Or reply to this email.`,
    ``,
    `You can check your booking status at any time:`,
    `  https://cardetail1.netlify.app/customer.html`,
    ``,
    `See you soon!`,
    `Cardetail1 Mobile Detailing`,
    `551-313-2956`,
  );

  try {
    const res = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${RESEND_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        from: RESEND_FROM || 'Cardetail1 <onboarding@resend.dev>',
        to:   [b.email],
        subject: `Your Cardetail1 appointment is confirmed — ${date}`,
        text: lines.join('\n'),
      }),
    });
    if (!res.ok) {
      const err = await res.text().catch(() => '');
      console.log('[update-booking] confirmation email failed:', res.status);
      return { sent: false, reason: `resend ${res.status}` };
    }
    console.log('[update-booking] confirmation email sent for', b.id);
    return { sent: true };
  } catch (e) {
    console.log('[update-booking] confirmation email error:', e.message);
    return { sent: false, reason: e.message };
  }
}

// ── Handler ──────────────────────────────────────────────────────────────────

exports.handler = async (event) => {
  currentEvent = event;
  if (event.httpMethod === 'OPTIONS') return json(204, {});
  if (event.httpMethod !== 'POST')    return json(405, { ok: false, error: 'method_not_allowed' });

  // ── Auth ──────────────────────────────────────────────────────────────────
  const expectedKey = (process.env.ADMIN_DASH_PASSWORD || '').trim();
  if (!expectedKey) return json(503, { ok: false, error: 'missing_admin_password_config' });

  const hdrs = event.headers || {};
  const providedKey = ((hdrs['x-admin-key'] || hdrs['X-Admin-Key']) || '').trim();
  if (!providedKey) return json(401, { ok: false, error: 'unauthorized' });

  const ka = Buffer.from(providedKey);
  const kb = Buffer.from(expectedKey);
  const match = ka.length === kb.length && crypto.timingSafeEqual(ka, kb);
  if (!match) return json(401, { ok: false, error: 'unauthorized' });

  // ── Parse body ────────────────────────────────────────────────────────────
  let body;
  try { body = JSON.parse(event.body || '{}'); }
  catch { return json(400, { ok: false, error: 'invalid_json' }); }

  // ── bookingId ─────────────────────────────────────────────────────────────
  const bookingId = typeof body.bookingId === 'string'
    ? body.bookingId.trim().toUpperCase().replace(/[^A-Z0-9-]/g, '')
    : '';
  if (!bookingId) return json(400, { ok: false, error: 'bookingId_required' });

  // ── updates object ────────────────────────────────────────────────────────
  const rawUpdates = body.updates;
  if (!rawUpdates || typeof rawUpdates !== 'object' || Array.isArray(rawUpdates)) {
    return json(400, { ok: false, error: 'updates_must_be_object' });
  }
  if (Object.keys(rawUpdates).length === 0) {
    return json(400, { ok: false, error: 'updates_empty' });
  }

  // ── Per-field validation ──────────────────────────────────────────────────
  const validated = {};
  for (const [key, value] of Object.entries(rawUpdates)) {
    if (BLOCKED_FIELDS.has(key)) {
      return json(400, { ok: false, error: 'field_not_allowed', field: key });
    }
    if (!ALLOWED_FIELDS.has(key)) {
      return json(400, { ok: false, error: 'unknown_field', field: key });
    }

    // Status enum checks
    if (key === 'appointmentStatus' && !ALLOWED_APPOINTMENT_STATUS.has(value)) {
      return json(400, { ok: false, error: 'invalid_appointmentStatus', received: value });
    }
    if (key === 'jobStatus' && !ALLOWED_JOB_STATUS.has(value)) {
      return json(400, { ok: false, error: 'invalid_jobStatus', received: value });
    }
    if (key === 'status' && !ALLOWED_LEGACY_STATUS.has(value)) {
      return json(400, { ok: false, error: 'invalid_status', received: value });
    }
    if (key === 'cancellationRequestStatus' && !CANCEL_REQ_STATUS.has(value)) {
      return json(400, { ok: false, error: 'invalid_cancellationRequestStatus', received: value });
    }
    if (URL_FIELDS.has(key)) {
      const url = safeHttpUrl(value, ['stripe.com', 'stripe.dev']);
      if (!url) return json(400, { ok: false, error: 'invalid_url', field: key });
      validated[key] = url.slice(0, URL_MAX);
      continue;
    }

    // Boolean validation
    if (BOOL_FIELDS.has(key) && typeof value !== 'boolean') {
      return json(400, { ok: false, error: 'field_must_be_boolean', field: key });
    }

    // Date/time must be strings
    if ((DATE_FIELDS.has(key) || TIME_FIELDS.has(key)) && typeof value !== 'string') {
      return json(400, { ok: false, error: 'field_must_be_string', field: key });
    }

    // Note sanitization
    validated[key] = NOTE_FIELDS.has(key) ? sanitize(value) : value;
  }

  // ── lastAction ────────────────────────────────────────────────────────────
  const lastAction = (typeof body.lastAction === 'string' && body.lastAction.trim())
    ? body.lastAction.trim().slice(0, 100)
    : 'admin_update_booking';

  // ── Blobs write ───────────────────────────────────────────────────────────
  try {
    const store   = await blobsStore('cd1-bookings');
    const booking = await store.get(bookingId, { type: 'json' }).catch(() => null);
    if (!booking) return json(404, { ok: false, error: 'booking_not_found' });

    // Archived / test protection — require explicit override.
    if ((booking.archived || booking.isTest) && !body.allowArchivedUpdate) {
      return json(403, {
        ok: false,
        error: 'booking_is_archived_or_test',
        hint: 'pass allowArchivedUpdate: true to override',
      });
    }

    const now = new Date().toISOString();
    const eventLog = Array.isArray(booking.eventLog) ? [...booking.eventLog] : [];
    eventLog.push({ action: lastAction, at: now, by: 'admin', fields: Object.keys(validated) });

    const patched = {
      ...booking,
      ...validated,
      updatedAt:      now,
      updatedByRole:  'admin',
      updatedBy:      'admin',
      lastAction,
      eventLog,
    };

    await store.setJSON(bookingId, patched);

    // Log field names only — never values, never notes, never secrets.
    console.log('[update-booking] ok', bookingId, 'admin', JSON.stringify(Object.keys(validated)), lastAction);

    // ── Confirmation email ────────────────────────────────────────────────
    // Sent when admin transitions appointmentStatus → "confirmed" or
    // legacy status → "Confirmed". Idempotent by prev-value check.
    const emailResults = {};
    const prevAppointmentStatus = booking.appointmentStatus || '';
    const prevStatus            = booking.status || '';
    const newAppointmentStatus  = validated.appointmentStatus || prevAppointmentStatus;
    const newStatus             = validated.status || prevStatus;

    const justConfirmed =
      (newAppointmentStatus === 'confirmed' && prevAppointmentStatus !== 'confirmed') ||
      (newStatus === 'Confirmed' && prevStatus !== 'Confirmed');

    if (justConfirmed) {
      emailResults.confirmationEmail = await sendConfirmationEmail(patched);
    }

    return json(200, {
      ok: true,
      bookingId,
      updatedFields: Object.keys(validated),
      updatedAt: now,
      lastAction,
      ...emailResults,
    });
  } catch (e) {
    console.error('[update-booking] error', bookingId, e.message);
    return json(500, { ok: false, error: 'update_failed' });
  }
};
